### ISSUE TITLE
possible issue with mrl remoteadapter service

### ISSUE THREAD

**Issue by CheekyMonkey** [MyRobotLab/inmoov#110] opened 2017-09-15 10:33 UTC
I'm seeing an exception in the mrl log when I attempt to make a remote adapter connection between two Raspberry Pi 3's

The remote adapter connection between the two Pis is failing as a result

[video](https://www.youtube.com/watch?v=EUvBbooTrSI) 

As the mrl GUI freezes after the remote adapter connection failure, I'm not able to send the mrl log through the menu in the mrl GUI so the mrl logs from each Raspberry Pi are being shared here for reference

[Raspberry Pi 3 - 1 myrobotlab.log.txt](https://github.com/MyRobotLab/inmoov/files/1306054/Raspberry.Pi.3.-.1.myrobotlab.log.txt)
[Raspberry Pi 3 - 2 myrobotlab.log.txt](https://github.com/MyRobotLab/inmoov/files/1306055/Raspberry.Pi.3.-.2.myrobotlab.log.txt)

![remoteadapter 2017-09-15 12 14 50](https://user-images.githubusercontent.com/537672/30480037-be21b28a-9a0f-11e7-951a-1645213a6e79.png)

**Comment by supertick** [comment] 2017-09-15 13:43
Wow .. this one of the most beautiful bug reports I have ever seen.
Clear, concise, even a Video ! 
Simply awesome.  Thanks !

So a couple of new non-serializable things got put into Runtime & SwingGui - this can make remote adapter connections explode BOOM.

This can be on-going issues as different services grow, so I'm getting the Test service to test this (Test service needs a little refactoring itself).

Fixed.

**Comment by CheekyMonkey** [comment] 2017-09-15 15:29
nice work supertick :)
now confirmed worky :)

[video](https://youtu.be/NPro2f4xZX8)
![remote adapter worky - 2017-09-15 16 26 26](https://user-images.githubusercontent.com/537672/30490782-ebf01972-9a32-11e7-9c64-10e4325aa43b.png)

**Comment by Cyber-One** [comment] 2017-09-15 23:32
Not so worky once you start to add services.
On remote Raspi,
# Fred01 startup Script

# This script is to  start each of the servo used in the InMoov Robot Fred.
# Fred consists of 3 Raspberry Pi 3.
# This is for the First Raspberry Pi 3 located in Fred's head and has the I2C servo interface card installed.

# There are 4 I2C servo controllers
head = Runtime.createAndStart("head", "Adafruit16CServoDriver")
rightArm = Runtime.createAndStart("rightArm", "Adafruit16CServoDriver")
leftArm = Runtime.createAndStart("leftArm", "Adafruit16CServoDriver")
back = Runtime.createAndStart("back", "Adafruit16CServoDriver")

#  This is all running off a Raspberry Pi 3
raspi = Runtime.createAndStart("raspi","RasPi")

# Now attach the servo drivers to the Raspberry Pi 3.
head.setController("raspi","1","0x40")
rightArm.setController("raspi","1","0x41")
leftArm.setController("raspi","1","0x42")
back.setController("raspi","1","0x43")

# Now lets create the servo functions

# We will Start with the Head
jaw = Runtime.createAndStart("jaw", "Servo")
jaw.attach(head,2)
jaw.setMinMax(0,180)

headX = Runtime.createAndStart("headX", "Servo")
headX.attach(head,3)
headX.setMinMax(0,180)

eyesX = Runtime.createAndStart("eyesX", "Servo")
eyesX.attach(head,0)
eyesX.setMinMax(0,180)


#  Right Arm
rightBicep = Runtime.createAndStart("rightBicep", "Servo")
rightBicep.attach(rightArm,15)
rightBicep.setMinMax(0,180)

rightElbow = Runtime.createAndStart("rightElbow", "Servo")
rightElbow.attach(rightArm,14)
rightElbow.setMinMax(0,180)

rightWrist = Runtime.createAndStart("rightWrist", "Servo")
rightWrist.attach(rightArm,0)
rightWrist.setMinMax(0,180)

rightThumb = Runtime.createAndStart("rightThumb", "Servo")
rightThumb.attach(rightArm,1)
rightThumb.setMinMax(0,180)

rightIndex = Runtime.createAndStart("rightIndex", "Servo")
rightIndex.attach(rightArm,2)
rightIndex.setMinMax(0,180)

rightMajure = Runtime.createAndStart("rightMajure", "Servo")
rightMajure.attach(rightArm,3)
rightMajure.setMinMax(0,180)

rightRing = Runtime.createAndStart("rightRing", "Servo")
rightRing.attach(rightArm,4)
rightRing.setMinMax(0,180)

rightLittle = Runtime.createAndStart("rightLittle", "Servo")
rightLittle.attach(rightArm,5)
rightLittle.setMinMax(0,180)


#  Left Arm
leftBicep = Runtime.createAndStart("leftBicep", "Servo")
leftBicep.attach(leftArm,15)
leftBicep.setMinMax(0,180)

leftElbow = Runtime.createAndStart("leftElbow", "Servo")
leftElbow.attach(leftArm,14)
leftElbow.setMinMax(0,180)

leftWrist = Runtime.createAndStart("leftWrist", "Servo")
leftWrist.attach(leftArm,0)
leftWrist.setMinMax(0,180)

leftThumb = Runtime.createAndStart("leftThumb", "Servo")
leftThumb.attach(leftArm,1)
leftThumb.setMinMax(0,180)

leftIndex = Runtime.createAndStart("leftIndex", "Servo")
leftIndex.attach(leftArm,2)
leftIndex.setMinMax(0,180)

leftMajure = Runtime.createAndStart("leftMajure", "Servo")
leftMajure.attach(leftArm,3)
leftMajure.setMinMax(0,180)

leftRing = Runtime.createAndStart("leftRing", "Servo")
leftRing.attach(leftArm,4)
leftRing.setMinMax(0,180)

leftLittle = Runtime.createAndStart("leftLittle", "Servo")
leftLittle.attach(leftArm,5)
leftLittle.setMinMax(0,180)


#  Back
backHeadY = Runtime.createAndStart("backHeadY", "Servo")
backHeadY.attach(back,8)
backHeadY.setMinMax(0,180)

backHeadRoll = Runtime.createAndStart("backHeadRoll", "Servo")
backHeadRoll.attach(back,9)
backHeadRoll.setMinMax(0,180)

backTopStomach = Runtime.createAndStart("backTopStomach", "Servo")
backTopStomach.attach(back,10)
backTopStomach.setMinMax(0,180)

backMidStomach = Runtime.createAndStart("backMidStomach", "Servo")
backMidStomach.attach(back,11)
backMidStomach.setMinMax(0,180)

backRightOmo = Runtime.createAndStart("backRightOmo", "Servo")
backRightOmo.attach(back,15)
backRightOmo.setMinMax(0,180)

backRightShoulder = Runtime.createAndStart("backRightShoulder", "Servo")
backRightShoulder.attach(back,14)
backRightShoulder.setMinMax(0,180)

backLeftOmo = Runtime.createAndStart("backLeftOmo", "Servo")
backLeftOmo.attach(back,0)
backLeftOmo.setMinMax(0,180)

backLeftShoulder = Runtime.createAndStart("backLeftShoulder", "Servo")
backLeftShoulder.attach(back,1)
backLeftShoulder.setMinMax(0,180)

# now lets start the RemoteAdapter Service. As this will be headless, we will listen.
remote = Runtime.createAndStart("remote","RemoteAdapter")

remote.startListening()

on the local Windows 7 Machine
remoteAdapterB = Runtime.createAndStart("RemoteAdapterB","RemoteAdapter")

remoteAdapterB.setDefaultPrefix("Fred02")

# Change to the ip address of the remote host
remoteAdapterB.connect("tcp://192.168.1.22:6767")

Both machine are running RML 1.0.2502

The local machine creates the RemoteAdapterB service and the Fred02log service
Both machines then lockup, hence no worky post when is attempt to connect Fred02RightArm.

Excerpt from the local log
remoteAdapterB = Runtime.createAndStart("RemoteAdapterB","RemoteAdapter")

remoteAdapterB.setDefaultPrefix("Fred02")

# Change to the ip address of the remote host
remoteAdapterB.connect("tcp://192.168.1.22:6767")
09:05:45.670 [python.interpreter.8] INFO c.m.s.Runtime [Runtime.java:353] Runtime.createService RemoteAdapterB
09:05:45.670 [python.interpreter.8] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:135] RemoteAdapterB.connecting tcp://192.168.1.22:6767
09:05:45.670 [python.interpreter.8] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:45.924 [runtime] WARN c.m.f.Service [Service.java:1384] no such method Runtime.register(Log,URI) :  - attempting upcasting
09:05:45.924 [RemoteAdapterB] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:45.924 [runtime] WARN c.m.f.Service [Service.java:1389] searching through 276 methods
09:05:45.924 [runtime] INFO c.m.f.Service [Service.java:1950] subscribe [Fred02log/publishState ---> runtime/onState]
09:05:45.924 [python] WARN c.m.f.Service [Service.java:1384] no such method Python.onRegistered(Log) :  - attempting upcasting
09:05:45.924 [python] WARN c.m.f.Service [Service.java:1389] searching through 179 methods
09:05:45.924 [python] INFO c.m.s.Python [Python.java:466] exec(String) 
from org.myrobotlab.service import Log
Fred02log = Runtime.getService("Fred02log")

09:05:45.924 [gui] WARN c.m.f.Service [Service.java:1384] no such method SwingGui.addTab(Log) :  - attempting upcasting
09:05:45.924 [gui] WARN c.m.f.Service [Service.java:1389] searching through 207 methods
09:05:45.924 [gui] WARN c.m.f.Service [Service.java:1384] no such method RuntimeGui.onRegistered(Log) :  - attempting upcasting
09:05:45.924 [gui] WARN c.m.f.Service [Service.java:1389] searching through 76 methods
09:05:45.940 [AWT-EventQueue-0] INFO c.m.s.SwingGui [SwingGui.java:302] createTab Fred02log org.myrobotlab.swing.LogGui
09:05:45.940 [AWT-EventQueue-0] INFO c.m.f.Service [Service.java:1950] subscribe [Fred02log/publishStatus ---> gui/onStatus]
09:05:45.940 [RemoteAdapterB] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.018 [runtime] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.018 [RemoteAdapterB] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.018 [runtime] WARN c.m.f.Service [Service.java:1384] no such method Runtime.register(Adafruit16CServoDriver,URI) :  - attempting upcasting
09:05:46.018 [runtime] WARN c.m.f.Service [Service.java:1389] searching through 276 methods
09:05:46.018 [runtime] WARN c.m.f.Service [Service.java:1384] no such method Runtime.registered(Adafruit16CServoDriver) :  - attempting upcasting
09:05:46.018 [runtime] WARN c.m.f.Service [Service.java:1389] searching through 276 methods
09:05:46.018 [runtime] INFO c.m.f.Service [Service.java:1950] subscribe [Fred02rightArm/publishState ---> runtime/onState]
09:05:46.018 [python] WARN c.m.f.Service [Service.java:1384] no such method Python.onRegistered(Adafruit16CServoDriver) :  - attempting upcasting
09:05:46.018 [python] WARN c.m.f.Service [Service.java:1389] searching through 179 methods
09:05:46.018 [python] INFO c.m.s.Python [Python.java:466] exec(String) 
from org.myrobotlab.service import Adafruit16CServoDriver
Fred02rightArm = Runtime.getService("Fred02rightArm")

09:05:46.018 [gui] WARN c.m.f.Service [Service.java:1384] no such method SwingGui.addTab(Adafruit16CServoDriver) :  - attempting upcasting
09:05:46.018 [gui] WARN c.m.f.Service [Service.java:1389] searching through 207 methods
09:05:46.018 [gui] WARN c.m.f.Service [Service.java:1384] no such method RuntimeGui.onRegistered(Adafruit16CServoDriver) :  - attempting upcasting
09:05:46.018 [gui] WARN c.m.f.Service [Service.java:1389] searching through 76 methods
09:05:46.018 [RemoteAdapterB] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.079 [RemoteAdapterB:tcp://192.168.1.22:6767] ERROR c.m.l.Logging [Logging.java:19] ------
java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: java.lang.Object
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readArray(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at org.myrobotlab.net.TcpThread.run(TcpThread.java:97)
Caused by: java.io.NotSerializableException: java.lang.Object
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.myrobotlab.net.TcpThread.send(TcpThread.java:308)
	at org.myrobotlab.net.TcpServer.sendTcp(TcpServer.java:156)
	at org.myrobotlab.service.RemoteAdapter.sendRemoteTCP(RemoteAdapter.java:306)
	at org.myrobotlab.service.RemoteAdapter.sendRemote(RemoteAdapter.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.myrobotlab.framework.Service.invokeOn(Service.java:1351)
	at org.myrobotlab.framework.Service.invoke(Service.java:1287)
	at org.myrobotlab.framework.Service.run(Service.java:1672)
	at java.lang.Thread.run(Thread.java:745)
------

09:05:46.079 [RemoteAdapterB:tcp://192.168.1.22:6767] ERROR c.m.n.TcpThread [TcpThread.java:65] removing mrl://RemoteAdapterB/tcp://192.168.1.22:6767 from registry
09:05:46.079 [RemoteAdapterB:tcp://192.168.1.22:6767] INFO c.m.s.Runtime [Runtime.java:1495] releasing url mrl://RemoteAdapterB/tcp://192.168.1.22:6767
09:05:46.251 [AWT-EventQueue-0] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.251 [gui_outbox_0] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.251 [AWT-EventQueue-0] INFO c.m.f.Service [Service.java:1950] subscribe [Fred02log/publishState ---> gui/onState]
09:05:46.251 [AWT-EventQueue-0] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.251 [RemoteAdapterB] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.273 [runtime] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.277 [RemoteAdapterB:tcp://192.168.1.22:6767] INFO c.m.s.Runtime [Runtime.java:1459] releasing service Fred02log
09:05:46.277 [RemoteAdapterB] INFO c.m.s.RemoteAdapter [RemoteAdapter.java:292] sendRemote tcp://192.168.1.22:6767
09:05:46.278 [RemoteAdapterB:tcp://192.168.1.22:6767] WARN c.m.f.Service [Service.java:1384] no such method Runtime.released(Log) :  - attempting upcasting
09:05:46.278 [RemoteAdapterB:tcp://192.168.1.22:6767] WARN c.m.f.Service [Service.java:1389] searching through 276 methods
09:05:46.279 [RemoteAdapterB:tcp://192.168.1.22:6767] INFO c.m.s.Runtime [Runtime.java:1483] released Fred02log
09:05:46.279 [RemoteAdapterB:tcp://192.168.1.22:6767] INFO c.m.s.Runtime [Runtime.java:1459] releasing service Fred02rightArm
09:05:46.280 [RemoteAdapterB:tcp://192.168.1.22:6767] WARN c.m.f.Service [Service.java:1384] no such method Runtime.released(Adafruit16CServoDriver) :  - attempting upcasting
09:05:46.280 [RemoteAdapterB:tcp://192.168.1.22:6767] WARN c.m.f.Service [Service.java:1389] searching through 276 methods
09:05:46.280 [RemoteAdapterB:tcp://192.168.1.22:6767] INFO c.m.s.Runtime [Runtime.java:1483] released Fred02rightArm
09:05:46.280 [RemoteAdapterB:tcp://192.168.1.22:6767] ERROR c.m.n.TcpThread [TcpThread.java:69] shutting down thread
09:05:46.281 [RemoteAdapterB:tcp://192.168.1.22:6767] ERROR c.m.n.TcpThread [TcpThread.java:71] attempting to close streams
09:05:46.283 [RemoteAdapterB] ERROR c.m.f.Service [Service.java:2042] RemoteAdapterB error SocketException - Socket closed java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(Unknown Source)
	at java.io.ObjectOutputStream.writeNonProxyDesc(Unknown Source)
	at java.io.ObjectOutputStream.writeClassDesc(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeFatalException(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at org.myrobotlab.net.TcpThread.send(TcpThread.java:308)
	at org.myrobotlab.net.TcpServer.sendTcp(TcpServer.java:156)
	at org.myrobotlab.service.RemoteAdapter.sendRemoteTCP(RemoteAdapter.java:306)
	at org.myrobotlab.service.RemoteAdapter.sendRemote(RemoteAdapter.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.myrobotlab.framework.Service.invokeOn(Service.java:1351)
	at org.myrobotlab.framework.Service.invoke(Service.java:1287)
	at org.myrobotlab.framework.Service.run(Service.java:1672)
	at java.lang.Thread.run(Unknown Source)

**Comment by supertick** [comment] 2017-09-16 14:57
Thanks Cyber-One ..
I like your startup, in that you fully decomposed all the pieces I assume for the I2C control of the servos.
Bravo !

I'll re-open this ticket and look into it

**Comment by supertick** [comment] 2017-09-16 16:38
Servo was borked with non-transient moveToBlocked lock - fixed in build 2504

**Closed by supertick** 2017-09-16 16:38 UTC

**Comment by CheekyMonkey** [comment] 2017-09-16 18:18
Thanks Grog, nice work again :)

Raspberry Pi 3/AdaFruit16C I2C connected servos/Remote Adapter service confirmed worky  with development build 2505

[Video](https://www.youtube.com/watch?v=ZvQ7h4jXdt0&feature=youtu.be)

![mrl remote adapter build 2505 2017-09-16 19 16 20](https://user-images.githubusercontent.com/537672/30514771-b93ef8fe-9b13-11e7-8291-e2da3fe1853c.png)
